### ISSUE TITLE
[docs] Update exisiting `README`

### ISSUE THREAD

**Issue by Aryamanz29** [Aryamanz29/Web-Ideas#195]
- I found some of the section in project README have errors that need to be correct and I'm also thinking of improving overall[ project README](https://github.com/Aryamanz29/Web-Ideas/blob/master/README.md).
-  Some of the errors are shown below :
```
1. git pull upstream main (correction : we are using master as default branch)

2. Write commit message as "Small Message" 

git commit -m "Write a meaningfull but small commit message" 

(correction: better to mention proper commit message guidelines to maintain consistency, I would suggest to use : (https://www.conventionalcommits.org/en/v1.0.0/))
```
There are lots of area for improvement, let me know more in issue thread before proceeding further :)

**Comment by akhilsharmaa** [comment]
I like to work on this.

**Comment by adityasingh10042** [comment]
Hey, I want to work on this. Please assign this to me!

**Comment by Aryamanz29** [comment]
@adityasingh10042 Go ahead 👍🏻

**Comment by Aryamanz29** [comment]
@akhilsharmaa I have opened a general issue for all here : https://github.com/Aryamanz29/Web-Ideas/issues/198, Please read issue description carefully and send us PR :)
