### ISSUE TITLE
[directory] Categorise projects to different directories

### ISSUE THREAD

**Issue by Aryamanz29** [Aryamanz29/Web-Ideas#196]
- It would be better to move similar types of project ideas to separate directory eg. `static-sites/, django/, js/` etc

**Comment by Asmit2952** [comment]
I would like to work on this

**Comment by adityasingh10042** [comment]
Hey, I want to work on this. Please assign this to me!

**Comment by Aryamanz29** [comment]
@Asmit2952 Go ahead :100:
