### ISSUE TITLE
[docs] Add a new section for `Available Web Ideas`

### ISSUE THREAD

**Issue by Aryamanz29** [Aryamanz29/Web-Ideas#197]
- It would be better to have a section consisting all `Available Web Ideas` (maybe we can add them to a table?)

**Comment by Asmit2952** [comment]
Would like to work on this as well. This will be related to changing directories issue #196 as I would have to link the different directories here

**Comment by adityasingh10042** [comment]
Hey, I want to work on this. Please assign this to me!

**Comment by Aryamanz29** [comment]
@Asmit2952 Go ahead with this one :+1:
