### ISSUE TITLE
[qa] The PR template needs to be updated

### ISSUE THREAD

**Issue by Aryamanz29** [Aryamanz29/Web-Ideas#199]
- Currently PR template missing project conditions for valid `Web-Idea`
  - Here are some of checkpoints I found missing in current PR template :-
 ```
Some conditions PR needs to follow: 

- Project must follow good coding practices.
- Project must be related  to web development only.
- Project  must be added to their respective category directory eg. `React/, Django/, Php/` etc.
- It must have proper documentation (it would be better if it had demos or screenshots).
- Avoid raising Spam PR's
 ```

**Comment by Aryamanz29** [comment]
`PR template `: https://github.com/Aryamanz29/Web-Ideas/blob/master/.github/Pull_Request_Template.md

**Comment by deepeshaburse** [comment]
I would like to work on this

**Comment by Aryamanz29** [comment]
@deepeshaburse Sure, Go ahead 👍🏻

**Comment by pranjal6314** [comment]
I would like to work on this.

**Comment by neeraj542** [comment]
Hii, can I work on this issue for my First pull request
